services:
  neo4j:
    image: neo4j:5.11.0-community-bullseye
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4j222
    volumes:
      - ~/deployment/airflow/data/:/var/lib/neo4j/import
