services:
  neo4j:
    image: neo4j-mexico
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4j222
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - ~/deployment/airflow/data/:/var/lib/neo4j/import
    networks:
      - mexico_net
networks:
  mexico_net:
